version: '3'
services:
  askpostgres:
    container_name: askpostgres
    build: .
    env_file: .env
    ports:
      - 5435:5432
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - .:/app
    environment:
      - DATABASE_URL=postgres://postgres:postgres@localhost:5432/postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432